project:
  type: website
  output-dir: docs

website:
  cookie-consent: true
  bread-crumbs: true
  title: "Lorenzo Mattioli"
  navbar:
    style: docked
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        href: Projects.qmd
    right:
      - icon: instagram
        href: https://www.instagram.com/ermattaraus/
      - icon: github
        href: https://github.com/lorMatt
      - icon: envelope
        href: mailto:lorenzo.mattioli5@studio.unibo.it
format:
  html:
    theme: simplex
    css: styles.css

editor: visual

